---
name: REUSE Compliance

on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
