name: Publish

on:
  push:
    tags:
      - "release-[0-9]+.[0-9]+.[0-9]+"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create artifact
        run: ./gradlew clean publish

      - name: Maven Central Upload
        env:
          JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USER }}
          JRELEASER_MAVENCENTRAL_SONATYPE_TOKEN: ${{ secrets.SONATYPE_PWD }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.SIGNING_KEY_ID }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.SIGNING_PWD }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.SIGNING_KEY }}
        run: ./gradlew jreleaserDeploy
